p8105_hw1_xw2961
================
2024-09-21

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Load the dataset

``` r
data("penguins", package = "palmerpenguins")
```

# QUESTION 1: data description

``` r
?penguins
```

    ## No documentation for 'penguins' in specified packages and libraries:
    ## you could try '??penguins'

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(penguins$flipper_length_mm, na.rm=TRUE)
```

    ## [1] 200.9152

``` r
ggplot(data=penguins,aes(x = bill_length_mm, y = flipper_length_mm)) + geom_point(aes(color = species), na.rm=TRUE)
```

![](p8105_hw1_xw2961_files/figure-gfm/unnamed-chunk-1-1.png)<!-- --> -
The dataset penguins consists of 8 variables: species, island,
bill_length_mm,bill_depth_mm, flipper_length_mm,body_mass_g,sex,year -
`species`: The species of penguin. - `island`: the island in which the
kind of species live in - `bill_length_mm`: Length of the penguin’s bill
in millimeters. - `bill_depth_mm`: Depth of the penguin’s bill in
millimeters. - `flipper_length_mm`: Length of the penguin’s flipper in
millimeters. - `body_mass_g`: Body mass of the penguin in grams. -
`sex`: The sex of the penguin (male or female).

- Number of rows: 344

- Number of column: 8

- Mean flipper length=200.92

\#QUESTION 2: Creating a data frame

``` r
Data_Frame <- data.frame(
              samp =rnorm(10),
              Character_vector = c("Lusa", "is", "good", "perfect", "beautiful", "charming", "hard working","good at R", "nice","very nice"),
              Factor_vector = factor(rep(c("low", "medium", "high"), length.out = 10)))
Data_Frame$Logical_vector = Data_Frame$samp > 0
```

``` r
mean(Data_Frame[["samp"]])
```

    ## [1] -0.03012241

``` r
mean(Data_Frame[["Logical_vector"]])
```

    ## [1] 0.5

``` r
mean(Data_Frame[["Character_vector"]])
```

    ## Warning in mean.default(Data_Frame[["Character_vector"]]): argument is not
    ## numeric or logical: returning NA

    ## [1] NA

``` r
mean(Data_Frame[["Factor_vector"]])
```

    ## Warning in mean.default(Data_Frame[["Factor_vector"]]): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

The dataset with numerical value can have the mean, and the dataset with
categorical value cannot output the mean.

``` r
# Convert the logical, character, and factor variables to numeric
logical_as_numeric <- as.numeric(Data_Frame$Logical_vector)   
character_as_numeric <- as.numeric(Data_Frame$Character_vector)  
```

    ## Warning: NAs introduced by coercion

``` r
factor_as_numeric <- as.numeric(Data_Frame$Factor_vector)
```

Logical to Numeric: Works and provides the proportion of TRUE values
because TRUE is treated as 1 and FALSE as 0. Character to Numeric: Does
not work and produces NAs, because characters cannot be directly
converted to numeric. Factor to Numeric: Works, but it’s important to
note that the result represents the mean of the integer codes associated
with the factor levels, which may not be meaningful unless you’re aware
of the factor’s internal ordering.
